name: Re-deploy site

on:
  workflow_dispatch:
  schedule:
    # Every Monday at 12:00 UTC
    - cron: '0 12 * * 1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call webhook
        run: curl -X GET "https://api.vercel.com/v1/integrations/deploy/${{ secrets.DEPLOY_URL_HASH }}"
